firstName: str = input("Please enter your first name: ")
lastName = input("Please enter your last name: ")
age = int(input("Please enter your age: "))
salary = float(input("Please enter your salary: "))
postCode = input("Please enter your postal code: ")

print("first name:", firstName)
print("last name:", lastName)
print("age:", age)
print("salary:", salary)
print("postal code:", postCode)
